name: Compile JOSS Paper

on:
  push:
    paths:
      - 'paper.md'
      - 'paper.bib'
  pull_request:

jobs:
  build-paper:
    runs-on: ubuntu-latest
    name: Build paper

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup TeX environment
        uses: xu-cheng/latex-action@v3
        with:
          root_file: paper.md
          compiler: latexmk
          args: "-pdf -interaction=nonstopmode -output-directory=output"

      - name: Upload paper PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-paper
          path: output/paper.pdf
